dist: trusty
sudo: required

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

git:
    depth: 1

language: scala

scala:
- 2.12.1

jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.ivy2

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export DOCKERHOST=`$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)`
  - cd /home/travis/build/dhlab-basel/Knora/salsah/lib/chromedriver/ && unzip chromedriver_linux64.zip

script:
# start fuseki
- cd /home/travis/build/dhlab-basel/Knora/triplestores/fuseki/ && ./fuseki-server &
# start the built-in webapi server tests
- cd /home/travis/build/dhlab-basel/Knora/webapi/ && sbt test
# start the sipi container in the background (needed for salsah tests)
- docker run -d --add-host webapihost:$DOCKERHOST -p 1024:1024 dhlabbasel/sipi:wip-travis-testing
# start the webapi server (needed for salsah tests)
- cd /home/travis/build/dhlab-basel/Knora/webapi/ && sbt "run allowResetTriplestoreContentOperationOverHTTP" &
# wait for the webapi server to start before we proceed with running the salsah tests
- until netstat -an 2>/dev/null | grep '3333.*LISTEN'; do true; done
# start built-in salsah browser tests
- cd /home/travis/build/dhlab-basel/Knora/salsah/ && sbt test

notifications:
  slack:
    secure: AJZARDC7P6bwjFwk6gpe+p2ozLj+bH3h83PapfCTL0xi7frHd4y6/jXOs9ac+m7ia5FlnzgBxrf0lmaE+IkqlRzxo5dPNYkDIbMC3nrf48kS+uQjf87X1Pn6bDVBLL56L1xIeaEXAqLLWNZ8m1UQ3ykVHgUbUbimjm43eCMpUiretgOqQgreZuLGVxPDU4KrGYZ93FvT2Nzp1Iagld0KXJ1up/uKlpSZAIpJPhgWYIhSGwj9hYG50iENvtsOX/zTe2hjhKWaPmVxHWo8qNyyHfX/+3ODQhvKu3LQsFXbW8WQ1r86EUDrGWeT6mlCYbjR1Wk/7wEKvGts/7vnTNJ8H2xDG9ADc4zIzIpnz0+gndIXuguxuMZEdm1H9okcDqraa4OV01bobr43RVC4hTZCiEBt7wCd/c+C1lJahAQUQoKsbmp5idKrjUyESJ0ZbU6hgkKeOvEvUqv0msYJGWW/C5BlUlro08AgZ9h6nOfu8jJQ49x9QbSWLjTVDg8CEq3w8FDATGA6FKdDqgmsi/3ROjgdewPgyxE3XZ2UpAbAdMPeuGvFoU91X8gScm6ys6abLy0vdCL3LyqmBu/Vzdg1RzU7oqUqSbR5LSMh8pwAwy26j6Awp+pDEzBtyL59yN6r6wgxmbJ5KT+XJReEH6Ao0C6ay23E8T/3YmI3qbjX8xE=
