version: "3"

services:

  sipi:
    image: nieine/sipi
    ports:
      - 1024:1024
    volumes:
      - ./tmp:/tmp
      - $HOME:$HOME
      - ./images:/sipi/images
      - ../Knora/webapiTemp:/tmp/webapi_tmp/
      - ../KnoSaSi-PrenuiltImages/sipiConfig:/sipi/config
    networks:
      - knora

  graphdb:
    image: dhlabbasel/graphdb-free
    ports:
      - 7200:7200
    networks:
      - knora

  webapi:
    build: ./Knora
    ports:
      - 3333:3333
    depends_on:
      - graphdb
    volumes:
      - ./Knora/webapi/src/main:/Knora/webapi/src/main
      - ./webapiTmp:/tmp/webapi_tmp/
    networks:
      - knora
    depends_on:
      - graphdb
      - sipi



  salsah1:
    build: salsah/
    context: salsah/
    ports:
      - 3335:3335
    networks:
      - knora
    depends_on:
      - webapi

  salsah2:
    build: salsah2/
      context: salsah2/
      ports:
        - 4200:4200

netorks:
  knora:
    driver: bridge
