version: '3.7'

services:

  app:
    image: daschswiss/dsp-app:v10.23.5
    ports:
      - "4200:4200"
    networks:
      - knora-net

  db:
    image: daschswiss/apache-jena-fuseki:2.1.2 # should be the same version as in Dependencies.scala, also make sure to use the same version when deploying it (i.e. version in ops-deploy)!
    ports:
      - "3030:3030"
    volumes:
      - db-home:/fuseki:delegated
      - db-import:/staging:delegated
    networks:
      - knora-net
    environment:
      - TZ=Europe/Zurich
      - ADMIN_PASSWORD=test
      - JVM_ARGS=-Xmx3G

  sipi:
    image: daschswiss/knora-sipi:latest

    ports:
      - "1024:1024"
    volumes:
      - /tmp:/tmp
      - ${LOCAL_HOME}/sipi/config:/sipi/config:delegated
      - ${LOCAL_HOME}/sipi/images:/sipi/images:delegated
      - ${LOCAL_HOME}/sipi/server:/sipi/server:delegated
      - ${LOCAL_HOME}/sipi/scripts:/sipi/scripts:delegated
    networks:
      - knora-net
    environment:
      - TZ=Europe/Zurich
      - SIPI_EXTERNAL_PROTOCOL=http
      - SIPI_EXTERNAL_HOSTNAME=0.0.0.0
      - SIPI_EXTERNAL_PORT=1024
      # Use the following line if you start the api as a docker container from this docker-compose.yml
      # - SIPI_WEBAPI_HOSTNAME=api
      # Use the following line if you start the api from your IDE
      - SIPI_WEBAPI_HOSTNAME=host.docker.internal
      - SIPI_WEBAPI_PORT=3333
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_HOST=0.0.0.0
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_PORT=3333
      - CLEAN_TMP_DIR_USER=clean_tmp_dir_user
      - CLEAN_TMP_DIR_PW=clean_tmp_dir_pw
    # entrypoint: [ "valgrind", "--leak-check=yes", "/sipi/sipi" ] ## uncomment to run SIPI under valgrind
    # command: --config=/sipi/config/sipi.docker-test-config.lua ## command variant to start the sipi container with test routes enabled
    command: --config=/sipi/config/sipi.docker-config.lua

  ingest:
    image: daschswiss/dsp-ingest:latest
    ports:
      - "3340:3340"
    volumes:
      - ${LOCAL_HOME}/sipi/images:/opt/images:delegated
      - ${LOCAL_HOME}/sipi/tmp-dsp-ingest:/opt/temp:delegated
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=3340
      - SERVICE_LOG_FORMAT=text
      - STORAGE_ASSET_DIR=/opt/images
      - STORAGE_TEMP_DIR=/opt/temp
      - JWT_AUDIENCE=http://localhost:3340
      - JWT_ISSUER=0.0.0.0:3333
      - JWT_SECRET=UP 4888, nice 4-8-4 steam engine
      - SIPI_USE_LOCAL_DEV=false
#      - JWT_DISABLE_AUTH=true # Uncomment this line if you want to disable authentication for the ingest service

  api:
    image: daschswiss/knora-api:latest
    ports:
      - "3333:3333"
      - "5555:5555"
      - "3339:3339"
    volumes:
      - /tmp:/tmp
    networks:
      - knora-net
    environment:
      - TZ=Europe/Zurich
      - KNORA_AKKA_LOGLEVEL=DEBUG
      - KNORA_AKKA_STDOUT_LOGLEVEL=DEBUG
      - KNORA_WEBAPI_TRIPLESTORE_HOST=db
      - KNORA_WEBAPI_TRIPLESTORE_DBTYPE=fuseki
      - KNORA_WEBAPI_SIPI_INTERNAL_HOST=sipi
      - KNORA_WEBAPI_TRIPLESTORE_FUSEKI_REPOSITORY_NAME=${KNORA_DB_REPOSITORY_NAME}
      - KNORA_WEBAPI_TRIPLESTORE_FUSEKI_USERNAME=admin
      - KNORA_WEBAPI_TRIPLESTORE_FUSEKI_PASSWORD=test
      - KNORA_WEBAPI_CACHE_SERVICE_ENABLED=true
      - KNORA_WEBAPI_ALLOW_RELOAD_OVER_HTTP=true
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_HOST=0.0.0.0
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_PORT=3333
      - KNORA_WEBAPI_DSP_INGEST_AUDIENCE=http://localhost:3340
      - KNORA_WEBAPI_DSP_INGEST_BASE_URL=http://ingest:3340
      # - DSP_API_LOG_APPENDER=JSON # if this variable is set, JSON logs are activated locally

networks:
  knora-net:
    name: knora-net

volumes:
  db-home:
  db-import:
