# Please define the following environment variables:
# - KNORA_GDB_LICENSE - path to the GraphDB-SE license file
# - KNORA_GDB_HOME - path to a local folder where GraphDB should store it's data
#
# - KNORA_GDB_IMAGE - is defined in the .env file in this directory. If you would like to use GraphDB-Free, then
# set environment variable with something like KNORA_GDB_IMAGE=dhlabbasel/graphdb-free:8.3.1

version: '3'

services:

  graphdb:
    image: ${KNORA_GDB_IMAGE}
    ports:
    - "7200:7200"
    volumes:
    - ${KNORA_GDB_LICENSE}:/graphdb/GRAPHDB_SE.license
    - ${KNORA_GDB_HOME}:/opt/graphdb/home:delegated
    - ${PWD}/webapi/scripts/KnoraRules.pie:/graphdb/KnoraRules.pie
    networks:
    - knora-net
    environment:
    - GDB_HEAP_SIZE=2G
    - GDB_JAVA_OPTS=-Dgraphdb.license.file=/graphdb/GRAPHDB_SE.license -Dgraphdb.home=/opt/graphdb/home
    command: ["/graphdb/bin/graphdb"]
    container_name: graphdb

  sipi:
    image: dhlabbasel/sipi:develop
    ports:
    - "1024:1024"
    volumes:
    - /tmp:/tmp
    - ${PWD}/sipi/config:/sipi/config
    - ${PWD}/sipi/scripts:/sipi/scripts
    - ${PWD}/sipi/images:/sipi/images:delegated
    - ${PWD}/sipi/server:/sipi/server:delegated
    networks:
    - knora-net
    restart: unless-stopped
    command: --config=/sipi/config/sipi.knora-docker-it-config.lua
    container_name: sipi

  webapi:
    image: dhlabbasel/scala-sbt
    ports:
    - "3333:3333"
    - "10001:10001"
    volumes:
    - /tmp:/tmp
    - ${HOME}/.sbt:/root/.sbt:delegated
    - ${HOME}/.ivy2:/root/.ivy2:delegated
    - ${PWD}:/src:delegated
    networks:
    - knora-net
    environment:
    - KNORA_DB_HOST=graphdb
    - KNORA_SIPI_HOST=sipi
    command: [
      "sh", "-c",
      "cd webapi && sbt clean && sbt stage && cd target/universal/stage && ./bin/webapi -J-agentpath:/usr/local/YourKit-JavaProfiler-2018.04/bin/linux-x86-64/libyjpagent.so=port=10001,listen=all -J-Xms1G J-Xmx1G"
    ]
    container_name: webapi

  salsah1:
    build:
      context: salsah1/
    image: dhlabbasel/salsah1
    ports:
    - "3335:3335"
    networks:
    - knora-net
    environment:
    - KNORA_SALSAH1_HOSTNAME=0.0.0.0
    - KNORA_SALSAH1_PORT=3335
    - KNORA_SALSAH1_WEBAPI=http://0.0.0.0:3333
    - KNORA_SALSAH1_SIPI=http://0.0.0.0:1024
    container_name: salsah1

networks:
  knora-net:
