version: '3.7'

services:

  db:
    image: daschswiss/apache-jena-fuseki:2.0.8 # should be the same version as in Dependencies.scala
    ports:
      - "3030:3030"
    volumes:
      - db-home:/fuseki:delegated
      - db-import:/staging:delegated
    networks:
      - knora-net
    environment:
      - TZ=Europe/Zurich
      - ADMIN_PASSWORD=test
      - JVM_ARGS=-Xmx3G

  sipi:
    image: daschswiss/knora-sipi:latest

    ports:
      - "1024:1024"
    volumes:
      - /tmp:/tmp
      - ${LOCAL_HOME}/sipi/config:/sipi/config:delegated
      - ${LOCAL_HOME}/sipi/images:/sipi/images:delegated
      - ${LOCAL_HOME}/sipi/server:/sipi/server:delegated
    networks:
      - knora-net
    environment:
      - TZ=Europe/Zurich
      - SIPI_EXTERNAL_PROTOCOL=http
      - SIPI_EXTERNAL_HOSTNAME=0.0.0.0
      - SIPI_EXTERNAL_PORT=1024
      - SIPI_WEBAPI_HOSTNAME=api
      - SIPI_WEBAPI_PORT=3333
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_HOST=0.0.0.0
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_PORT=3333
    # entrypoint: [ "valgrind", "--leak-check=yes", "/sipi/sipi" ] ## uncomment to run SIPI under valgrind
    command: --config=/sipi/config/sipi.docker-config.lua

  api:
    image: daschswiss/knora-api:latest
    ports:
      - "3333:3333"
    volumes:
      - /tmp:/tmp
    networks:
      - knora-net
    environment:
      - TZ=Europe/Zurich
      - KNORA_AKKA_LOGLEVEL=DEBUG
      - KNORA_AKKA_STDOUT_LOGLEVEL=DEBUG
      - KNORA_WEBAPI_DB_CONNECTIONS=2
      - KNORA_WEBAPI_TRIPLESTORE_HOST=db
      - KNORA_WEBAPI_TRIPLESTORE_DBTYPE=fuseki
      - KNORA_WEBAPI_SIPI_INTERNAL_HOST=sipi
      - KNORA_WEBAPI_TRIPLESTORE_FUSEKI_REPOSITORY_NAME=${KNORA_DB_REPOSITORY_NAME}
      - KNORA_WEBAPI_TRIPLESTORE_FUSEKI_USERNAME=admin
      - KNORA_WEBAPI_TRIPLESTORE_FUSEKI_PASSWORD=test
      - KNORA_WEBAPI_CACHE_SERVICE_ENABLED=true
      - KNORA_WEBAPI_CACHE_SERVICE_REDIS_HOST=redis
      - KNORA_WEBAPI_CACHE_SERVICE_REDIS_PORT=6379
      - KNORA_WEBAPI_ALLOW_RELOAD_OVER_HTTP=true
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_HOST=0.0.0.0
      - KNORA_WEBAPI_KNORA_API_EXTERNAL_PORT=3333

networks:
  knora-net:
    name: knora-net

volumes:
  db-home:
  db-import:
