version: '3'

services:

  graphdb:
    image: ontotext/graphdb:8.5.0-se
    ports:
    - "7200:7200"
    volumes:
    - ${PWD}/webapi/scripts/KnoraRules.pie:/graphdb/KnoraRules.pie
    - ${PWD}/triplestores/graphdb/GRAPHDB_SE.license:/graphdb/GRAPHDB_SE.license
    - ${PWD}/triplestores/graphdb/home:/opt/graphdb/home:delegated
    networks:
    - knora-net
    environment:
    - GDB_HEAP_SIZE=2G
    - GDB_JAVA_OPTS=-Dgraphdb.license.file=/graphdb/GRAPHDB_SE.license -Dgraphdb.home=/opt/graphdb/home
    command: ["/graphdb/bin/graphdb"]
    container_name: graphdb

  sipi:
    image: dhlabbasel/sipi:develop
    ports:
    - "1024:1024"
    volumes:
    - /tmp:/tmp
    - ${PWD}/sipi/config:/sipi/config
    - ${PWD}/sipi/scripts:/sipi/scripts
    - ${PWD}/sipi/images:/sipi/images:delegated
    - ${PWD}/sipi/server:/sipi/server:delegated
    networks:
    - knora-net
    extra_hosts:
    - webapihost:0.0.0.0
    restart: unless-stopped
    command: --config=/sipi/config/sipi.knora-docker-it-config.lua
    container_name: sipi

  webapi:
    image: dhlabbasel/scala-sbt
    ports:
    - "3333:3333"
    - "10001:10001"
    volumes:
    - /tmp:/tmp
    - ${HOME}/.sbt:/root/.sbt:delegated
    - ${HOME}/.ivy2:/root/.ivy2:delegated
    - ${PWD}:/src:delegated
    networks:
    - knora-net
    environment:
    - KNORA_DB_HOST=graphdb
    - KNORA_SIPI_HOST=sipi
    command: [
      "sh", "-c",
      "cd webapi && sbt clean && sbt stage && cd target/universal/stage && ./bin/webapi -J-agentpath:/usr/local/YourKit-JavaProfiler-2018.04/bin/linux-x86-64/libyjpagent.so=port=10001,listen=all -J-Xms1G J-Xmx1G"
    ]
    container_name: webapi

networks:
  knora-net:
