site_name: Knora Documentation

nav:
  - Introduction:
      - Overview: 01-introduction/index.md
      - What is Knora?: 01-introduction/what-is-knora.md
      - Data Formats in Knora: 01-introduction/data-formats.md
      - Standoff/RDF Text Markup: 01-introduction/standoff-rdf.md
      - An Example Project: 01-introduction/example-project.md
  - Knora Ontologies:
      - Overview: 02-knora-ontologies/index.md
      - Introduction: 02-knora-ontologies/introduction.md
      - The Knora Base Ontology: 02-knora-ontologies/knora-base.md
      - The SALSAH GUI Ontology: 02-knora-ontologies/salsah-gui.md
  - APIs:
      - The Knora APIs:
          - Overview: 03-apis/index.md
      - API V1:
          - Overview: 03-apis/api-v1/index.md
          - Introduction: 03-apis/api-v1/introduction.md
          - Authentication: 03-apis/api-v1/authentication.md
          - Reading and Searching Resources: 03-apis/api-v1/reading-and-searching-resources.md
          - XML to Standoff Mapping: 03-apis/api-v1/xml-to-standoff-mapping.md
          - Adding Resources: 03-apis/api-v1/adding-resources.md
          - Reading and Searching Resources: 03-apis/api-v1/reading-and-searching-resources.md
          - Reading Values: 03-apis/api-v1/reading-values.md
          - Adding Values: 03-apis/api-v1/adding-values.md
          - Changing Values: 03-apis/api-v1/changing-values.md
          - Deleting Resources and Values: 03-apis/api-v1/deleting-resources-and-values.md
#  - APIs:
#  - Publishing and Deployment:
#  - Internals:
#  - Salsah:
#  - SIPI:
  - Lucene:
      - Overview: 08-lucene/index.md
      - Lucene Query Parser Syntax: 08-lucene/lucene-query-parser-syntax.md
  - Release Notes:
      - Overview: 00-release-notes/index.md
      - Migration Notes: 00-release-notes/migration.md
      - Next Release: 00-release-notes/next.md
      - v1.1.0: 00-release-notes/v1.1.0.md
      - v1.2.0: 00-release-notes/v1.2.0.md
      - v1.3.0: 00-release-notes/v1.3.0.md
      - v1.4.0: 00-release-notes/v1.4.0.md
      - v1.5.0: 00-release-notes/v1.5.0.md
      - v1.6.0: 00-release-notes/v1.6.0.md
      - v1.7.0: 00-release-notes/v1.7.0.md
      - v2.x.x: 00-release-notes/v2.x.x.md
      - v3.x.x: 00-release-notes/v3.x.x.md
      - v4.x.x: 00-release-notes/v4.x.x.md
      - v5.x.x: 00-release-notes/v5.x.x.md
      - v6.x.x: 00-release-notes/v6.x.x.md

theme:
  name: material
  logo: 'assets/images/dasch-icon-white.svg'
  favicon: 'assets/images/dasch-favicon.ico'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  features:
    - tabs
extra_css:
  - 'assets/style/theme.css'
