schemaVersion: 2.0.0

metadataTest:
  entrypoint: ['/sipi/sipi']
  cmd: [
    '--config=/sipi/config/sipi.config.lua'
  ]

fileExistenceTests:
- name: 'sipi.binary'
  path: '/sipi/sipi'
  shouldExist: true

- name: 'sipi.config.lua'
  path: '/sipi/config/sipi.config.lua'
  shouldExist: true

- name: 'sipi.init.lua'
  path: '/sipi/config/sipi.init.lua'
  shouldExist: true

- name: 'test.html'
  path: '/sipi/server/test.html'
  shouldExist: true
