version: '3.7'

services:

  db:
    image: ${KNORA_GRAPHDB_IMAGE}
    ports:
      - "7200:7200"
    volumes:
      - ${KNORA_GDB_LICENSE_FILE}:/graphdb/graphdb.license
      - ${KNORA_GDB_IMPORT_DIR}:/root/graphdb-import
      - db-data:/opt/graphdb/home
    networks:
      - knora-net
    environment:
    - GDB_HEAP_SIZE=$KNORA_GDB_HEAP_SIZE
    - GDB_JAVA_OPTS=-Dgraphdb.license.file=/graphdb/graphdb.license -Dgraphdb.home=/opt/graphdb/home
    command: ["/graphdb/bin/graphdb"]

  sipi:
    image: ${KNORA_SIPI_IMAGE}
    ports:
      - "1024:1024"
    volumes:
      - /tmp:/tmp
      - ${PWD}/sipi/config:/sipi/config
      - ${PWD}/sipi/images:/sipi/images:delegated
      - ${PWD}/sipi/server:/sipi/server:delegated
    networks:
      - knora-net
    restart: unless-stopped
    environment:
      - SIPI_EXTERNAL_PROTOCOL=http
      - SIPI_EXTERNAL_HOSTNAME=sipi
      - SIPI_EXTERNAL_PORT=1024
      - SIPI_WEBAPI_HOSTNAME=api
      - SIPI_WEBAPI_PORT=3333
    command: --config=/sipi/config/sipi.knora-docker-config.lua

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - knora-net

  api:
    image: ${KNORA_API_IMAGE}
    ports:
      - "3333:3333"
      - "10001:10001"
    volumes:
      - /tmp:/tmp
    networks:
      - knora-net
    environment:
      - KNORA_AKKA_LOGLEVEL=DEBUG
      - KNORA_AKKA_STDOUT_LOGLEVEL=DEBUG
      - KNORA_WEBAPI_TRIPLESTORE_HOST=db
      - KNORA_WEBAPI_TRIPLESTORE_DBTYPE=${KNORA_GDB_TYPE}
      - KNORA_WEBAPI_SIPI_INTERNAL_HOST=sipi
      - KNORA_WEBAPI_TRIPLESTORE_GRAPHDB_REPOSITORY_NAME=knora-test
      - KNORA_WEBAPI_CACHE_SERVICE_ENABLED=true
      - KNORA_WEBAPI_CACHE_SERVICE_REDIS_HOST=redis
      - KNORA_WEBAPI_CACHE_SERVICE_REDIS_PORT=6379
      - KNORA_WEBAPI_ALLOW_RELOAD_OVER_HTTP=true

  salsah1:
    image: ${KNORA_SALSAH1_IMAGE}
    ports:
      - "3335:3335"
    networks:
      - knora-net
    environment:
      - KNORA_SALSAH1_HOSTNAME=0.0.0.0
      - KNORA_SALSAH1_PORT=3335
      - KNORA_SALSAH1_WEBAPI=http://0.0.0.0:3333
      - KNORA_SALSAH1_SIPI=http://0.0.0.0:1024

networks:
  knora-net:

volumes:
  db-data:
  db-import:
  no-license: