# GraphDB-SE local test
---
- dbtype: graphdb
- https: false
- host: localhost
- port: 7200
- dbname: knora-test
- version: develop
- rules: ../webapi/scripts/KnoraRules.pie
- data:
  - path: ../knora-ontologies/knora-base.ttl
    name: http://www.knora.org/ontology/knora-base
  - path: ../knora-ontologies/knora-admin.ttl
    name: http://www.knora.org/ontology/knora-base
  - path: ../knora-ontologies/standoff-onto.ttl
    name: http://www.knora.org/ontology/standoff
  - path: ../knora-ontologies/standoff-data.ttl
    name: http://www.knora.org/data/standoff
  - path: ../knora-ontologies/salsah-gui.ttl
    name: http://www.knora.org/ontology/salsah-gui
  - path: ../webapi/_test_data/all_data/admin-data.ttl
    name: http://www.knora.org/data/admin
  - path: ../webapi/_test_data/all_data/permissions-data.ttl
    name: http://www.knora.org/data/permissions
  - path: ../webapi/_test_data/all_data/system-data.ttl
    name: http://www.knora.org/data/0000/SystemProject
  - path: ../webapi/_test_data/ontologies/incunabula-onto.ttl
    name: http://www.knora.org/ontology/0803/incunabula
  - path: ../webapi/_test_data/all_data/incunabula-data.ttl
    name: http://www.knora.org/data/0803/incunabula
  - path: ../webapi/_test_data/ontologies/dokubib-onto.ttl
    name: http://www.knora.org/ontology/0804/dokubib
  - path: ../webapi/_test_data/ontologies/images-onto.ttl
    name: http://www.knora.org/ontology/00FF/images
  - path: ../webapi/_test_data/demo_data/images-demo-data.ttl
    name: http://www.knora.org/data/00FF/images
  - path: ../webapi/_test_data/ontologies/anything-onto.ttl
    name: http://www.knora.org/ontology/0001/anything
  - path: ../webapi/_test_data/all_data/anything-data.ttl
    name: http://www.knora.org/data/0001/anything
  - path: ../webapi/_test_data/ontologies/something-onto.ttl
    name: http://www.knora.org/ontology/0001/something
  - path: ../webapi/_test_data/ontologies/beol-onto.ttl
    name: http://www.knora.org/ontology/0801/beol
  - path: ../webapi/_test_data/ontologies/biblio-onto.ttl
    name: http://www.knora.org/ontology/0802/biblio
  - path: ../webapi/_test_data/all_data/biblio-data.ttl
    name: http://www.knora.org/data/0802/biblio
  - path: ../webapi/_test_data/all_data/beol-data.ttl
    name: http://www.knora.org/data/0801/beol
  - path: ../webapi/_test_data/ontologies/webern-onto.ttl
    name: http://www.knora.org/ontology/08AE/webern
  - path: ../webapi/_test_data/all_data/webern-data.ttl
    name: http://www.knora.org/data/08AE/webern

