name: "Preparation"
description: "Preparation steps to run tests"

runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK  ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java }}
        cache: sbt
