name: "Preparation"
description: "Preparation steps to run tests"

runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 50
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"
    - name: Install requirements (apt)
      run: sudo apt-get install ca-certificates-java expect unzip
      shell: bash
    - name: Coursier cache
      uses: coursier/cache-action@v6
