name: "Preparation"
description: "Preparation steps to run tests"

runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"
        cache: sbt
