name: Publish to Dockerhub

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - name: Build and publish images to Dockerhub
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} --password-stdin ${{ secrets.DOCKER_HUB_TOKEN }}
          make publish-all-images
