name: Docker Publish from branch

on:
  workflow_dispatch:

jobs:
  publish-from-branch:
    name: Publish from branch
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.output_docker_image_tag.outputs.tag }}
    steps:
      - name: Run preparatory steps
        uses: dasch-swiss/dsp-api/.github/actions/preparation@main
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and publish dsp-api image to Dockerhub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          make docker-publish-dsp-api-image
      # - name: Build and publish sipi images to Dockerhub
      #   run: |
      #     echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      #     make docker-publish-sipi-image
      - name: Output docker image tag
        id: output_docker_image_tag
        run: echo "tag=$(make docker-image-tag | tr -d '\n')" >> "$GITHUB_OUTPUT"
        shell: bash # Explicit for fail-fast behaviour
