name: publish-to-dockerhub

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: publish to dockerhub
        run: docker login --username $DOCKER_USER | $DOCKER_HUB_TOKEN && make publish-all-images
