name: run-upgrade-tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: run upgrade tests
      run: cd upgrade && pip3 install -r requirements.txt && ./test.sh
