name: Test Repository Upgrade

on:
  push:
  workflow_dispatch:

jobs:
  upgrade-integration-tests:
    name: Test repository upgrade
    runs-on: ubuntu-latest
    steps:
      - name: Run preparatory steps
        uses: dasch-swiss/dsp-api/.github/actions/preparation@239cd15685155ade0f7904a8ba8ab310d611a789
      - name: Test repository upgrade
        run: make test-repository-upgrade
      - name: Dump docker logs on failure using different shell
        uses: jwalton/gh-docker-logs@v1
        with:
          shell: "/bin/sh"
      - name: Cleanup cache
        uses: dasch-swiss/dsp-api/.github/actions/cleanup@239cd15685155ade0f7904a8ba8ab310d611a789
