name: Upgrade integration test
description: Tests if upgrade scripts run successfully

on:
  workflow_dispatch:

jobs:
  upgrade-integration-tests:
    name: Upgrade integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Run preparatory steps
        uses: dasch-swiss/dsp-api/.github/actions@23afe175d58d7e1a56cc77684aa16240a6ecb05a
      - name: Test repository upgrade
        run: make test-repository-upgrade
      - name: Dump docker logs on failure using different shell
        uses: jwalton/gh-docker-logs@v1
        with:
          shell: "/bin/sh"
      - name: Cleanup before cache
        shell: bash
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
